  version:  '3'
  services:
  
  
    mysql:
      image:  mysql:5.7
      ports:
        -  3306:3306
      environment:
        MYSQL_ROOT_PASSWORD:  Kit@mysql4
        MYSQL_DATABASE: accountmanager  
      healthcheck:
        test:  "exit 0"
        
    mongo:
      image: mongo:3.4.20-xenial
      ports:
        -  27017:27017
      container_name:  mongo  
      healthcheck:
        test:  "exit 0"
        
    rabbitmq:
      image:  rabbitmq:management
      ports:
        -  15672:15672 
        -  5672:5672
      healthcheck:
        test:  "exit 0"
        
    accountmanager:
      image:  akizhaku/manager-gipher
      restart:  always
      depends_on:
        -  mysql
        -  eurekaserver
      ports:
        -  8089:8089
      healthcheck:
        test:  "exit 0"
        
    gipherrecommendersystem:
      image:  akizhaku/recommender-gipher
      restart:  always
      depends_on:
        -  mongo
        -  eurekaserver
        -  rabbitmq
      ports:
        -  9200:9200
      healthcheck:
        test:  "exit 0"
        
    giphermanager:
      image:  akizhaku/manager-gipher
      restart:  always
      depends_on:
        -  mongo
        -  eurekaserver
        -  rabbitmq
      ports:
        -  9100:9100
      healthcheck:
        test:  "exit 0"
        
    zuulapigateway:
      image:  akizhaku/zuul-api-gipher
      restart:  always
      depends_on:
        - eurekaserver
      ports:
        -  8765:8765
      healthcheck:
        test:  "exit 0"
        
    eurekaserver:
      image:  akizhaku/eureka-gipher
      restart:  always
      ports:
        -  8761:8761
      healthcheck:
        test:  "exit 0"
                  
                  