FROM java:8
WORKDIR /Users/Shared
ADD /target/gipherrecommendersystem-1.0.jar /Users/Shared/gipherrecommendersystem-1.0.jar
EXPOSE 9200:9200
ENTRYPOINT ["java" ,"-jar","gipherrecommendersystem-1.0.jar"]